---
layout: cv
title: Austin Allen's CV
---
# Austin Allen
Student at BYU-Idaho. 

<div id="webaddress">
<a href="austallen99@gmail.com">austallen99@gmail.com</a>
| <a href="www.linkedin.com/in/austin-allen-b914911b7">My Linkedin page</a>
</div>

### Skills

C++, C#, Python, Git, Github, R

### Experiential Learning Projects
ME 172 | BYU-Idaho	Jan – Apr 2024

Student	Rexburg, ID            

•	Certified Solid Works Associate

•	Technical Drawing, Parametric Modeling, Assembly Design, Design Analysis, CAD Best Practices 

### Education

Brigham Young University-Idaho Est. Dec 2025

### Occupation

#### BYU-Idaho Aux Maintenance	Sep 2020 – Present

Maintenance Technician	Rexburg, ID            

•	Conducted routine inspections and repairs of electrical and plumbing to ensure optimal functionality and safety within the housing complex 

•	Interacted professionally with residents, addressing maintenance concerns and providing excellent customer service to enhance resident satisfaction and retention

•	Developed robust testing and troubleshooting skills

#### Church of Jesus Christ of Latter-Day Saints	                  Mar 2019 – Mar 2020

Volunteer Service Representative	New England, USA

•	Corresponded effectively with people from diverse cultures and socioeconomic backgrounds

•	Assisted and supervised new Service Representatives

•	Oversaw and managed Service Representatives at district and area levels

#### Napa Auto Parts	                  Jun – Dec 2017

Parts Delivery Driver	Clackamas, OR/
•	Planned and executed delivery routes/
•	Arranged and organized store inventory for ease of operation/
•	Ability to work well independently and as part of a team to prioritize tasks in a fast-paced environment/
•	Excellent customer service and communication skills with local stores and customers/



### Footer

Last updated: Sep 2024